require 'rubygems'
require 'rdoc/task'

########################################################################
# Description tasks
########################################################################
task :default => [:run]

task :tests => [:unit_tests]

task :unit_tests => [ :test_image,
                      :test_transform,
                      :test_resampler]

task :run do
  sh %{bin/resampling}
end

task :measure do
  sh %{cd lib/performance; ruby resample_benchmark.rb}
end
########################################################################


########################################################################
# Test Unitaire
########################################################################
task :test_image do
  sh %{rake test TEST=test/test_image}
end
task :test_transform do
  sh %{rake test TEST=test/test_transform}
end
task :test_resampler do
  sh %{rake test TEST=test/test_resampler}
end
########################################################################

Rake::RDocTask.new do |rd|
  rd.main = "README.rdoc"
  rd.rdoc_files.include("README.rdoc","lib/**/*.rb","bin/**/*")
  rd.title = 'Your application title'
end

require 'rake/testtask'
Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList['test/*_test.rb']
end

task :default => [:test,:features]
